console.log("Teste 1");
console.log("Teste 2");
console.log("Teste 3");
console.log("Teste 4");
console.log("Teste 5");
console.log("Teste 6");
console.log("Teste 7");
console.log("Teste 8");
console.log("Teste 9");
console.log("Outro teste 1");
console.log("Outro teste 2");
console.log("Outro teste 3");
console.log("Outro teste 4");
console.log("Outro teste 3");
console.log("Outro teste 4");
console.log("Outro teste 5");
console.log("Outro teste 6");
console.log("Outro teste 7");
console.log("Outro teste 8");
console.log("Outro teste 9");
console.log("Código aí");
console.log("Código aí 2");
console.log("Código aí 3");
console.log("Código aí 4");
console.log("Código aí 5");
console.log("Código aí 6");
console.log("Código aí 7");
console.log("Código aí 8");
console.log("Código aí 9");
console.log("Código aí 10");
console.log("Código aí 11");