console.log("Teste 1");
console.log("Teste 2");
console.log("Teste 3");
console.log("Teste 4");
console.log("Teste 5");
console.log("Teste 6");
console.log("Teste 7");
console.log("Teste 8");
console.log("Teste 9");
console.log("Teste 10");
console.log("Teste 11");
console.log("Teste 12");
console.log("Teste 13");
console.log("Teste 14");
console.log("Outro teste 1");
console.log("Outro teste 2");
console.log("Outro teste 3");
console.log("Outro teste 4");
console.log("Outro teste 3");
console.log("Outro teste 4");
console.log("Outro teste 5");
console.log("Outro teste 6");
console.log("Outro teste 7");
console.log("Outro teste 8");
console.log("Outro teste 9");
console.log("Outro teste 10");
console.log("Outro teste 11");
console.log("Outro teste 12");
console.log("Outro teste 13");
console.log("Outro teste 14");
console.log("Código aí");
console.log("Código aí 2");
console.log("Código aí 3");
console.log("Código aí 4");
console.log("Código aí 5");
console.log("Código aí 6");
console.log("Código aí 7");
console.log("Código aí 8");
console.log("Código aí 9");
console.log("Código aí 10");
console.log("Código aí 11");
console.log("Código aí 12");
console.log("Código aí 13");
console.log("Código aí 14");
console.log("Código aí 15");
console.log("Código aí 16");
console.log("Código aí 17");
console.log("Código aí 18");
console.log("Código aí 19");
console.log("Código aí 20");
console.log("Código aí 21");
console.log("Código aí 22");
console.log("Código aí 23");
console.log("Código aí 24");
console.log("Código aí 25");
console.log("Código aí 26");
console.log("Código aí 27");
console.log("Código aí 28");
console.log("Código aí 29");
console.log("Código aí 30");
console.log("Código aí 31");
console.log("Código aí 32");
console.log("Código aí 33");
console.log("Código aí 34");
console.log("Código aí 35");
console.log("Código aí 36");
console.log("Código aí 37");
console.log("Código aí 38");
console.log("Código aí 39");
console.log("Código aí 40");
console.log("Código aí 41");
console.log("Código aí 42");
console.log("Código aí 43");
console.log("Código aí 44");
console.log("Código aí 45");
console.log("Código aí 46");
console.log("Código aí 47");
console.log("Código aí 48");
console.log("Código aí 49");
console.log("Código aí 50");
console.log("Código aí 51");
console.log("Código aí 52");
console.log("Código aí 53");
console.log("Código aí 54");
console.log("Código aí 55");
console.log("Código aí 56");
console.log("Código aí 57");
console.log("Código aí 58");
console.log("Código aí 59");
console.log("Código aí 60");
console.log("Código aí 61");
console.log("Código aí 62");
console.log("Código aí 63");
console.log("Código aí 64");
console.log("Código aí 65");
console.log("Código aí 66");